"""
templates.py - Template rendering and variable substitution for standup output.

All template variables are drawn from a fixed allowlist. Substitution is
bounded so neither template text nor variable values can produce runaway output.
"""

import re
from datetime import datetime

from standup.validator import (
    MAX_RENDERED_TEMPLATE_LENGTH,
    MAX_TEMPLATE_LENGTH,
    MAX_VARIABLE_VALUE_LENGTH,
    VALID_TEMPLATE_VARIABLES,
    validate_template_string,
)

# Backward-compatible alias used by test_templates.py
_MAX_RENDERED_LENGTH = MAX_RENDERED_TEMPLATE_LENGTH
_MAX_VARIABLE_VALUE_LENGTH = MAX_VARIABLE_VALUE_LENGTH


_BUILTIN_TEMPLATES: dict[str, str] = {
    "default": ("**Yesterday:** {yesterday}\n\n**Today:** {today}\n\n**Blockers:** {blockers}"),
    "slack": (
        ":wave: *Daily Standup — {date}*\n\n"
        "*Yesterday:* {yesterday}\n"
        "*Today:* {today}\n"
        "*Blockers:* {blockers}\n\n"
        "_Generated by StandupBot | {provider} | {commit_count} commit(s) across {repos}_"
    ),
    "minimal": "{yesterday} | {today} | {blockers}",
    "detailed": (
        "# Standup — {date} {time}\n\n"
        "## Yesterday\n{yesterday}\n\n"
        "## Today\n{today}\n\n"
        "## Blockers\n{blockers}\n\n"
        "---\n"
        "_Commits: {commit_count} | Repos: {repos} | Provider: {provider}_"
    ),
    "jira": ("[Standup {date}]\nDone: {yesterday}\nDoing: {today}\nImpediments: {blockers}"),
}
BUILTIN_TEMPLATES = _BUILTIN_TEMPLATES


def validate_custom_template(template_str: str) -> tuple[bool, str]:
    """Validate a custom template string. Alias for ``validate_template_string``."""
    return validate_template_string(template_str)


_SECTION_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    (
        "yesterday",
        re.compile(
            r"(?i)\*{0,2}(?:yesterday|done|completed|what i did|last|worked on)[:\s*]*\*{0,2}\s*(.+?)(?=\n\s*\*{0,2}(?:today|doing|planning|next|blockers|impediment)|$)",
            re.DOTALL,
        ),
    ),
    (
        "today",
        re.compile(
            r"(?i)\*{0,2}(?:today|doing|planning|next|working on|will do)[:\s*]*\*{0,2}\s*(.+?)(?=\n\s*\*{0,2}(?:blockers|impediment|blocker|yesterday|done)|$)",
            re.DOTALL,
        ),
    ),
    (
        "blockers",
        re.compile(
            r"(?i)\*{0,2}(?:blockers?|impediments?|blocked|stuck|challenges?|risks?|help needed)[:\s*]*\*{0,2}\s*(.+?)(?=\n\s*\*{0,2}(?:yesterday|today|done|doing)|$)",
            re.DOTALL,
        ),
    ),
]

_VARIABLE_TOKEN_RE = re.compile(r"\{([a-z_][a-z0-9_]*)\}")


def list_templates(custom_templates: dict[str, str] | None = None) -> list[str]:
    """
    Return the sorted list of available template names.

    Args:
        custom_templates: Optional user-defined templates to include.

    Returns:
        Sorted list of all template names.

    Raises:
        None.
    """
    names = set(_BUILTIN_TEMPLATES.keys())
    if isinstance(custom_templates, dict):
        names.update(custom_templates.keys())
    return sorted(names)


def get_template(name: str, custom_templates: dict[str, str] | None = None) -> str:
    """
    Return the template text for a given name.

    Args:
        name: Template name to look up.
        custom_templates: Optional user-defined templates.

    Returns:
        Template text.

    Raises:
        KeyError: If the named custom template exists but fails validation.
        ValueError: If the template name is not found in built-in or custom templates.
    """
    if isinstance(custom_templates, dict) and name in custom_templates:
        template_str = custom_templates[name]
        ok, message = validate_template_string(template_str)
        if ok:
            return template_str[:MAX_TEMPLATE_LENGTH]
        raise KeyError(f"Custom template {name!r} is invalid: {message}")
    if name in _BUILTIN_TEMPLATES:
        return _BUILTIN_TEMPLATES[name]
    raise ValueError(
        f"Template {name!r} not found. Run 'standup templates' to list available templates."
    )


def parse_llm_output(text: str) -> dict[str, str]:
    """
    Extract standup sections from raw LLM output.

    Args:
        text: Raw text returned by the LLM.

    Returns:
        Dict with ``yesterday``, ``today``, and ``blockers`` keys.

    Raises:
        None.
    """
    sections: dict[str, str] = {"yesterday": "", "today": "", "blockers": "None"}
    if not text or not text.strip():
        return sections

    for key, pattern in _SECTION_PATTERNS:
        match = pattern.search(text)
        if match:
            extracted = match.group(1).strip()
            extracted = re.sub(r"\*+", "", extracted).strip()
            extracted = re.sub(r"^[\[\]]+\s*", "", extracted).strip()
            if extracted:
                sections[key] = extracted

    if not any(sections[k] for k in ("yesterday", "today")):
        clean = re.sub(r"\*+", "", text).strip()
        sections["yesterday"] = clean[:500] if clean else ""

    return sections


def build_template_variables(
    raw_standup_text: str,
    commit_count: int = 0,
    repos: list[str] | None = None,
    provider: str = "",
    author_email: str = "",
    now: datetime | None = None,
) -> dict[str, str]:
    """
    Parse LLM output and assemble the full template substitution context.

    Args:
        raw_standup_text: Raw text from the LLM provider.
        commit_count: Number of commits included in this run.
        repos: List of repository names.
        provider: Provider slug used for this generation.
        author_email: Configured git author email.

    Returns:
        Mapping of template variable names to string values.

    Raises:
        None.
    """
    sections = parse_llm_output(raw_standup_text)
    if now is None:
        now = datetime.now()
    repo_str = ", ".join(repos) if repos else "n/a"
    return {
        "yesterday": sections.get("yesterday", ""),
        "today": sections.get("today", ""),
        "blockers": sections.get("blockers", "None"),
        "date": now.strftime("%Y-%m-%d"),
        "time": now.strftime("%H:%M"),
        "commit_count": str(commit_count),
        "repos": repo_str,
        "provider": str(provider),
        "author_email": str(author_email),
    }


def render_template(template_text: str, variables: dict[str, str]) -> str:
    """
    Substitute template variables using the allowlist and return bounded output.

    Args:
        template_text: Template string with ``{variable}`` placeholders.
        variables: Mapping of variable names to string values.

    Returns:
        Rendered template text capped to a safe maximum length.

    Raises:
        None.
    """
    if not template_text:
        return ""

    safe_vars: dict[str, str] = {}
    for key in VALID_TEMPLATE_VARIABLES:
        value = str(variables.get(key, ""))
        safe_vars[key] = value[:MAX_VARIABLE_VALUE_LENGTH]

    def _substitute(match: re.Match[str]) -> str:
        name = match.group(1)
        return safe_vars.get(name, match.group(0))

    try:
        result = _VARIABLE_TOKEN_RE.sub(_substitute, template_text)
    except Exception:
        result = template_text

    return result[:MAX_RENDERED_TEMPLATE_LENGTH]
